language: python
python:
        - "3.6"
        - "3.7"

addons:
        apt:
                packages:
                        - graphviz

install:
        - pip install -r requirements.txt

script:
        - ./run_tests.sh
